### PR TITLE
Improve display of class name and wrapping of test results 

### PR DESCRIPTION
**Pull request by damiani**
This PR fixes two display issues:

### Truncated class names

Class names get aggressively truncated unless the terminal window is quite wide. For example, when the window is 120 columns wide, the output looks like this:

screen shot 2017-12-22 at 12 03 01 am

Instead, this PR respects the `maxClassNameLength` setting (which I've adjusted to 50 characters):

screen shot 2017-12-22 at 12 04 01 am

When the window is too narrow for that many characters, it splits the class name / results display into two columns of equal widths. The result looks like this:

screen shot 2017-12-22 at 12 14 24 am

### Wrapping of test results

If test results extend beyond the edge of the window, they don't wrap/indent properly. Current behavior:

screen shot 2017-12-22 at 12 06 01 am

This fixes the display so 2nd and subsequent lines of results for a single test will properly wrap and align with the start of the previous line:

screen shot 2017-12-22 at 12 06 31 am

### CODE REVIEW

**Comment by benjamincrozat** [comment]
Can't wait for this fix to be implemented! I ran into the same issue.

**Comment by devinfd** [comment]
beautiful

**Comment by mikeerickson** [comment]
@benjamincrozat @devinfd This PR has been merged, now available in `0.4.0` version

**Comment by mikeerickson** [comment]
@damiani Thanks for PR, this has been on my "todo" list for quite sometime, but been slammed of late

**Comment by damiani** [comment]
@mikeerickson Happy to help!

**Comment by devinfd** [comment]
Already got it. Looks great, thanks!

Devin

**Comment by mikeerickson** [comment]
@devinfd 👍

**Pull request merged**
