### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bloggervista**
Broken Link. Better to add when fixed

### CODE REVIEW

**Comment by mfour-merickson** [comment]
@bloggervista wow, I had no idea this was down (this must have just happened recently).  Thanks for the heads up.  The "better" fix will be to fix the website issue.

**Comment by mfour-merickson** [comment]
@bloggervista I have addressed this, fixing the link to point to github repo (instead of removal)

**Comment by mikeerickson** [comment]
@bloggervista I have addressed this, fixing the link to point to github repo (instead of removal)

Sorry the last comments were from my work account :-)

**Comment by bloggervista** [comment]
no problem :)

**Pull request closed without merging**
