### PR TITLE
Replace symbols with emojis

### PR DESCRIPTION
**Pull request by mrcageman**
For a fun feature I though it would be nice to use emojis rather than the symbols.

### CODE REVIEW

**Comment by mikeerickson** [comment]
@mrcageman Well, that is surely "cute" but I dont think it is worthy of making it the default for all users.  However, I would consider making this a feature for a future version :-)

**Comment by ludo237** [comment]
@mrcageman maybe some sort of config file would do the trick

**Comment by mikeerickson** [comment]
@ludo237 There are a myriad of ways of handling it, just lower on the priority list.  This is the only request I have had for this feature so, you can understand :-)

**Comment by ludo237** [comment]
Sure I understand. I was just curious

**Comment by mikeerickson** [comment]
No worries, in this modern day and age, emojis are common place.  I will keep it on the feature list, never know I might get bored one Saturday and knock it out :-)

**Pull request closed without merging**
