### PR TITLE
Remove useless symfony/yaml . Add compatibility with newer hassankhan/config.

### PR DESCRIPTION
**Pull request by ddebin**
Remove useless coverage artifacts. Remove useless symfony/yaml from compose.json. Add compatibility with newer hassankhan/config.

### CODE REVIEW

**Comment by mikeerickson** [comment]
@ddebin What are you referring as symfony/yaml as useless?

**Comment by ddebin** [comment]
@mikeerickson Trying to upgrade symfony/yaml to ^5.0, I figured it's not used anywhere in the code. But, giving a second Thought, I see it may be needed by hassankhan/config if you want to parse YAML. But you can at least bump dependency to ^5.0.

**Comment by MLDMoritz** [comment]
See #160

**Comment by mikeerickson** [comment]
Items from this PR have been merged accordingly into current master branch.

**Pull request closed without merging**
