### PR TITLE
Support PHP 8.1

### LINKED ISSUE #176: Under PHP 8.1, this package (because of one of its dependencies) show deprecation notices
**What version of this package are you using?**
0.31.0

**What operating system, Node.js, and npm version?**
Mac, PHP 8.1

**What happened?**
```
Deprecated: Return type of Noodlehaus\AbstractConfig::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/mattstauffer/Sites/novapackages/vendor/hassankhan/config/src/AbstractConfig.php on line 183
```

**What did you expect to happen?**
No errors

**Are you willing to submit a pull request to fix this bug?**
Yep.

### PR DESCRIPTION
**Pull request by mattstauffer**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[x] Other, please explain: Updated PHP support

**What changes did you make? (Give an overview)**
Update `hassankhan/config` dependency to support `v3`, in order to support PHP 8.1.

**Which issue (if any) does this pull request address?**
Fixes #176 

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by dtvmedia** [comment]
@mikeerickson Any plan on when you could merge and release this?

**Comment by me-shaon** [comment]
@mikeerickson please merge this PR. We need this.

**Comment by iadambrown** [comment]
@mikeerickson just a friendly reminder this PR is still open :)

**Comment by mikeerickson** [comment]
Hey all, sorry I missed this.  I am away on vacation, but I will try and sneak away and get this reviewed/merged and released

**Pull request merged**
