### PR TITLE
fix infinite loop on windows fixes #37

### LINKED ISSUE #37: Terminal is hanging when starting phpunit on Windows
I just installed the extension and put 

`<phpunit printerClass="Codedungeon\PHPUnitPrettyResultPrinter\Printer">`

in my phpunit.xml

When trying to run phpunit the terminal just hangs. I can stop the script with ctrl+c, so it doesn't freeze the terminal. The problem is, nothing happens.

I am using Windows 10. Tried with the command prompt, Windows Powershell and GitBash.

### PR DESCRIPTION
**Pull request by peterlupu**

### CODE REVIEW

**Comment by sorincristea** [comment]
thanks peterlupu! It works for me!

**Comment by mikeerickson** [comment]
Awesome, thank you very much for the PR.  I will get this merged and tagged later this afternoon

**Comment by mikeerickson** [comment]
FYI, version 0.7.0 has been tagged, merging this PR
> thanks peterlupu! It works for me!
>

**Comment by JayAhrDE** [comment]
Got 0.17.1 installed and still get that message (without "class does not exist", though: there simply is no explanation in my case.

**Comment by mikeerickson** [comment]
@jayahrde would you mind removing completely and reinstall.  I am puzzled on this end as it works without issue using 0.17.1 on windows 10, PHPUnit 7.1 and php 7.1

**Comment by JayAhrDE** [comment]
Got to get back to it on my home machine, hope I won't forget.

**Comment by Zugmaschine** [comment]
Hello, i saw the solution, but i cant fix it. can you describe me, how i have to use that code solution? Is it to delete the green marked code, and add the red marked code at this place?
I use Windows 10 and the newes Version of Laravel Boilerplate.

**Comment by mikeerickson** [comment]
@zugmaschine this should already be available in the latest release.  What version do you have installed.

**Comment by Zugmaschine** [comment]
Hello Mike,
 thanks for your quick answer.
I use the latest version(5.6.34). So i wonder.
Do you have a idea?

Regards, Uwe

Am Di., 28. Aug. 2018 um 20:08 Uhr schrieb Mike Erickson <
notifications@github.com>:

**Pull request merged**
